module.exports = {
  name: 'orbit.js',
  out: 'docs',
  theme: 'default',
  exclude: ['**/node_modules/**', '**/*.spec.ts', '**/test/**'],
  excludePrivate: true,
  packages: [
    './packages/@orbit/coordinator',
    './packages/@orbit/core',
    './packages/@orbit/data',
    './packages/@orbit/identity-map',
    './packages/@orbit/immutable',
    './packages/@orbit/indexeddb',
    './packages/@orbit/indexeddb-bucket',
    './packages/@orbit/jsonapi',
    './packages/@orbit/local-storage',
    './packages/@orbit/local-storage-bucket',
    './packages/@orbit/memory',
    './packages/@orbit/record-cache',
    './packages/@orbit/records',
    './packages/@orbit/serializers',
    './packages/@orbit/utils',
    './packages/@orbit/validators',
  ]
};
