name: CI

on:
  pull_request: {}
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  lint:
    name: "Lint and compile"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn compile

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile
      - run: yarn test
